version: "3.9"

services:
  ixcsoft-back:
    build: ./ixcsoft-back
    container_name: ixcsoft-back
    restart: always
    entrypoint: sleep infinity
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      MONGO_URL_DEVELOPMENT: mongodb://root:example@mongo:27017/
      MONGO_URL_PRODUCTION: mongodb://root:example@mongo:27017/
      JWT_SECRET: 123456789
    ports: 
      - 3333:3333
    volumes:
      - ./ixcsoft-back:/usr/app

  ixcsoft-front:
    build: ./ixcsoft-front
    container_name: ixcsoft-front
    restart: always
    entrypoint: sleep infinity
    ports: 
      - 3000:3000
    environment:
      VITE_BACKEND_HOST: http://localhost:3333
    volumes:
      - ./ixcsoft-front:/usr/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
